### ISSUE TITLE
there're some error after I update vimsence

### ISSUE THREAD

**Issue by Innei** [hugolgst/vimsence#15] opened 2020-05-09 12:07 UTC
when I open nvim. show this error.
```
Error detected while processing function DiscordUpdatePresence[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/innei/.config/nvim/plugged/vimsence/python/vimsence.py", line 52, in update_presence
    if not rpc_obj.connected:
NameError: name 'rpc_obj' is not defined
```
and show this error when I open file.
```
Error detected while processing function DiscordAsyncWrapper:
line    9:
E15: Invalid expression: >timer_info()
E15: Invalid expression: s:timer->timer_info()
line   10:
E121: Undefined variable: info
E116: Invalid arguments for function len
E15: Invalid expression: len(info) == 1 && info[0]["paused"] == 0
```
how to fix? thanks

**Comment by LunarWatcher** [comment] 2020-05-09 12:11
Partial duplicate of #13 - not sure if Neovim works with all the timer stuff though.

**Comment by LunarWatcher** [comment] 2020-05-09 12:38
Try updating now. The PR to fix it got merged

**Comment by jakobkhansen** [comment] 2020-05-10 00:45
First error about rpc_obj still occurs for me on Neovim.
Adding `global rpc_obj` in first line of `update_presence()` fixed it though. I don't know anything about this codebase so I don't know if this breaks anything.

**Comment by LunarWatcher** [comment] 2020-05-10 07:35
I ran some local tests on some unrelated code, and I managed to repro it if `__init__` throws. What I'm guessing happens is that you're tripping the timeout, which raises a timeout error, and collapses the entire thing. I can try dropping the timeout, but I'm not sure how that affects the timers.

**Closed** 2020-05-16 01:50 UTC
